import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FaLinkedinIn, FaInstagram, FaFacebook } from 'react-icons/fa6'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mineirinho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id={`${styles.bgGreen}`}>
        <div style={{ display: 'flex', gap: 5, paddingRight: 20 }}>
          <FaInstagram color="#fff" />
          <FaFacebook color="#fff" />
          <FaLinkedinIn color="#fff" />
        </div>
      </div>
      <div id={`${styles.bgGreenLarger}`}></div>
    </>
  )
}
